# waypoint_interfaces/action/WaypointMission.action

# Goal
waypoint_interfaces/Waypoint[] waypoints
float64 default_max_speed
float64 default_acceleration
bool    loop
---
# Result
int8    status
uint32  completed_waypoints
uint32  total_waypoints
float64 total_distance
float64 elapsed_time
---
# Feedback
uint32  current_waypoint_id
uint32  current_segment_id
uint8   segment_action_type
uint8   segment_phase
float64 progress_percent
float64 distance_to_waypoint
float64 current_speed
float64 mission_elapsed_time
